var materials = "T5_MOUNT_OWL_FW_BRECILIEN,T6_MOUNT_HORSE,T8_MOUNT_MAMMOTH_TRANSPORT,QUESTITEM_TOKEN_MISTS,T6_MOUNT_ARMORED_HORSE,T5_METALBAR,T8_FARM_MOABIRD_FW_BRIDGEWATCH_GROWN,T8_MOUNTUPGRADE_HORSE_CURSE,T8_MOUNT_HORSE_UNDEAD,T8_FARM_DIREBEAR_GROWN,T4_FARM_GIANTSTAG_GROWN,T6_FARM_GIANTSTAG_MOOSE_GROWN,T6_MOUNT_SIEGE_BALLISTA,T7_PLANKS,T8_PLANKS,T8_MOUNT_ARMORED_HORSE_MORGANA,T5_FARM_COUGAR_GROWN,T6_FARM_OX_GROWN,T7_MOUNT_SWAMPDRAGON_AVALON_BASILISK,T8_FARM_GREYWOLF_FW_CAERLEON_GROWN,T6_FARM_HORSE_GROWN,T5_FARM_GREYWOLF_FW_CAERLEON_GROWN,T4_LEATHER,T3_MOUNT_OX,T8_METALBAR,T5_FARM_HORSE_GROWN,T8_MOUNT_ARMORED_HORSE_SKIN_01,T6_MOUNT_GIANTSTAG_MOOSE,T6_MOUNT_ARMORED_HORSE_SKIN_01,T5_MOUNT_HORSE,T6_METALBAR,T7_LEATHER,T6_FARM_DIREWOLF_GROWN,T7_MOUNT_ARMORED_HORSE,T8_MOUNT_OX,T6_MOUNT_OX,T8_MOUNT_DIREBEAR,T5_FARM_OWL_FW_BRECILIEN_GROWN,T5_MOUNT_ARMORED_HORSE,T1_FACTION_MOUNTAIN_TOKEN_1,T8_MOUNT_ARMORED_HORSE,T3_PLANKS,T3_FARM_OX_GROWN,T3_LEATHER,T5_MOUNT_SWAMPDRAGON_FW_THETFORD,QUESTITEM_TOKEN_AVALON,T8_MOUNT_GREYWOLF_FW_CAERLEON_ELITE,T7_CLOTH,T8_MOUNT_COUGAR_KEEPER,T7_METALBAR,T5_MOUNT_COUGAR_KEEPER,T8_FARM_RABBIT_EASTER_GROWN_DARK,T4_MOUNT_HORSE,T6_CLOTH,T5_FARM_OX_GROWN,T3_FARM_HORSE_GROWN,T8_FARM_OX_GROWN,T7_MOUNT_SWAMPDRAGON,T8_FARM_DIREBOAR_FW_LYMHURST_GROWN,T4_FARM_HORSE_GROWN,T5_FARM_DIREBEAR_FW_FORTSTERLING_GROWN,T3_MOUNT_HORSE,T8_MOUNT_DIREBOAR_FW_LYMHURST_ELITE,T8_FARM_RABBIT_EASTER_GROWN,T8_MOUNTUPGRADE_COUGAR_KEEPER,T8_MOUNTUPGRADE_HORSE_MORGANA,T5_MOUNT_DIREBOAR_FW_LYMHURST,T4_MOUNT_OX,T7_MOUNT_SWAMPDRAGON_BATTLE,T5_MOUNT_GREYWOLF_FW_CAERLEON,T6_MOUNT_DIREWOLF,T4_PLANKS,T8_FARM_HORSE_GROWN,T8_MOUNT_RABBIT_EASTER,T4_MOUNT_GIANTSTAG,T7_FARM_HORSE_GROWN,T8_FARM_DIREBEAR_FW_FORTSTERLING_GROWN,T8_MOUNT_SWAMPDRAGON_FW_THETFORD_ELITE,T8_MOUNT_MAMMOTH_BATTLE,T5_MOUNT_MOABIRD_FW_BRIDGEWATCH,T5_MOUNT_RAM_FW_MARTLOCK,T1_FACTION_HIGHLAND_TOKEN_1,T7_MOUNT_OX,T5_MOUNT_ARMORED_HORSE_SKIN_01,T8_MOUNT_OWL_FW_BRECILIEN_ELITE,T8_MOUNT_HORSE,T5_FARM_MOABIRD_FW_BRIDGEWATCH_GROWN,T5_FARM_DIREBOAR_FW_LYMHURST_GROWN,T8_FARM_RAM_FW_MARTLOCK_GROWN,T5_MOUNT_DIREBEAR_FW_FORTSTERLING,T5_FARM_RAM_FW_MARTLOCK_GROWN,T7_MOUNT_HORSE,T8_FARM_MAMMOTH_GROWN,T4_FARM_OX_GROWN,T7_FARM_OX_GROWN,T5_MOUNT_OX,T7_MOUNT_DIREBOAR,T8_LEATHER,T1_FACTION_CAERLEON_TOKEN_1,T5_FARM_SWAMPDRAGON_FW_THETFORD_GROWN,T5_CLOTH,T8_FARM_SWAMPDRAGON_FW_THETFORD_GROWN,T1_FACTION_FOREST_TOKEN_1,T8_MOUNT_RAM_FW_MARTLOCK_ELITE,T8_MOUNT_MOABIRD_FW_BRIDGEWATCH_ELITE,T7_MOUNT_ARMORED_HORSE_SKIN_01,T7_FARM_SWAMPDRAGON_GROWN,T6_LEATHER,T7_FARM_DIREBOAR_GROWN,T8_CLOTH,T8_FARM_OWL_FW_BRECILIEN_GROWN,T1_FACTION_SWAMP_TOKEN_1,UNIQUE_GVGTOKEN_GENERIC,T7_MOUNT_ARMORED_SWAMPDRAGON_BATTLE,T5_LEATHER,T6_PLANKS,T8_MOUNT_DIREBEAR_FW_FORTSTERLING_ELITE,T1_FACTION_STEPPE_TOKEN_1,T8_MOUNT_RABBIT_EASTER_DARK,T5_PLANKS,T5_MOUNT_COUGAR_KEEPER@1"
    var recipes = [
new Recipe("T3_MOUNT_HORSE", new Map([["T3_FARM_HORSE_GROWN", 1], ["T3_LEATHER", 20]]),["T3_FARM_HORSE_GROWN"],convertNut(160),1),
new Recipe("T3_MOUNT_OX", new Map([["T3_FARM_OX_GROWN", 1], ["T3_PLANKS", 30]]),["T3_FARM_OX_GROWN"],convertNut(240),1),
new Recipe("T4_MOUNT_HORSE", new Map([["T4_FARM_HORSE_GROWN", 1], ["T4_LEATHER", 20]]),["T4_FARM_HORSE_GROWN"],convertNut(320),1),
new Recipe("T4_MOUNT_OX", new Map([["T4_FARM_OX_GROWN", 1], ["T4_PLANKS", 30]]),["T4_FARM_OX_GROWN"],convertNut(480),1),
new Recipe("T4_MOUNT_GIANTSTAG", new Map([["T4_FARM_GIANTSTAG_GROWN", 1], ["T4_LEATHER", 20]]),["T4_FARM_GIANTSTAG_GROWN"],convertNut(320),1),
new Recipe("T5_MOUNT_HORSE", new Map([["T5_FARM_HORSE_GROWN", 1], ["T5_LEATHER", 20]]),["T5_FARM_HORSE_GROWN"],convertNut(640),1),
new Recipe("T5_MOUNT_ARMORED_HORSE", new Map([["T5_FARM_HORSE_GROWN", 1], ["T5_CLOTH", 10], ["T5_METALBAR", 20]]),["T5_FARM_HORSE_GROWN"],convertNut(960),1),
new Recipe("T5_MOUNT_OX", new Map([["T5_FARM_OX_GROWN", 1], ["T5_PLANKS", 30]]),["T5_FARM_OX_GROWN"],convertNut(960),1),
new Recipe("T5_MOUNT_MOABIRD_FW_BRIDGEWATCH", new Map([["T5_FARM_MOABIRD_FW_BRIDGEWATCH_GROWN", 1], ["T5_LEATHER", 20], ["T1_FACTION_STEPPE_TOKEN_1", 5]]),["T5_FARM_MOABIRD_FW_BRIDGEWATCH_GROWN", "T1_FACTION_STEPPE_TOKEN_1"],convertNut(640),1),
new Recipe("T5_MOUNT_DIREBEAR_FW_FORTSTERLING", new Map([["T5_FARM_DIREBEAR_FW_FORTSTERLING_GROWN", 1], ["T5_LEATHER", 20], ["T1_FACTION_MOUNTAIN_TOKEN_1", 5]]),["T5_FARM_DIREBEAR_FW_FORTSTERLING_GROWN", "T1_FACTION_MOUNTAIN_TOKEN_1"],convertNut(640),1),
new Recipe("T5_MOUNT_DIREBOAR_FW_LYMHURST", new Map([["T5_FARM_DIREBOAR_FW_LYMHURST_GROWN", 1], ["T5_LEATHER", 20], ["T1_FACTION_FOREST_TOKEN_1", 5]]),["T5_FARM_DIREBOAR_FW_LYMHURST_GROWN", "T1_FACTION_FOREST_TOKEN_1"],convertNut(640),1),
new Recipe("T5_MOUNT_RAM_FW_MARTLOCK", new Map([["T5_FARM_RAM_FW_MARTLOCK_GROWN", 1], ["T5_LEATHER", 20], ["T1_FACTION_HIGHLAND_TOKEN_1", 5]]),["T5_FARM_RAM_FW_MARTLOCK_GROWN", "T1_FACTION_HIGHLAND_TOKEN_1"],convertNut(640),1),
new Recipe("T5_MOUNT_SWAMPDRAGON_FW_THETFORD", new Map([["T5_FARM_SWAMPDRAGON_FW_THETFORD_GROWN", 1], ["T5_LEATHER", 20], ["T1_FACTION_SWAMP_TOKEN_1", 5]]),["T5_FARM_SWAMPDRAGON_FW_THETFORD_GROWN", "T1_FACTION_SWAMP_TOKEN_1"],convertNut(640),1),
new Recipe("T5_MOUNT_GREYWOLF_FW_CAERLEON", new Map([["T5_FARM_GREYWOLF_FW_CAERLEON_GROWN", 1], ["T5_LEATHER", 20], ["T1_FACTION_CAERLEON_TOKEN_1", 5]]),["T5_FARM_GREYWOLF_FW_CAERLEON_GROWN", "T1_FACTION_CAERLEON_TOKEN_1"],convertNut(640),1),
new Recipe("T5_MOUNT_OWL_FW_BRECILIEN", new Map([["T5_FARM_OWL_FW_BRECILIEN_GROWN", 1], ["T5_LEATHER", 20], ["QUESTITEM_TOKEN_MISTS", 5]]),["T5_FARM_OWL_FW_BRECILIEN_GROWN", "QUESTITEM_TOKEN_MISTS"],convertNut(960),1),
new Recipe("T5_MOUNT_COUGAR_KEEPER@1", new Map([["T5_FARM_COUGAR_GROWN", 1], ["T5_LEATHER", 20]]),["T5_FARM_COUGAR_GROWN"],convertNut(640),1),
new Recipe("T6_MOUNT_HORSE", new Map([["T6_FARM_HORSE_GROWN", 1], ["T6_LEATHER", 20]]),["T6_FARM_HORSE_GROWN"],convertNut(1280),1),
new Recipe("T6_MOUNT_ARMORED_HORSE", new Map([["T6_FARM_HORSE_GROWN", 1], ["T6_CLOTH", 10], ["T6_METALBAR", 20]]),["T6_FARM_HORSE_GROWN"],convertNut(1920),1),
new Recipe("T6_MOUNT_OX", new Map([["T6_FARM_OX_GROWN", 1], ["T6_PLANKS", 30]]),["T6_FARM_OX_GROWN"],convertNut(1920),1),
new Recipe("T6_MOUNT_GIANTSTAG_MOOSE", new Map([["T6_FARM_GIANTSTAG_MOOSE_GROWN", 1], ["T6_LEATHER", 20]]),["T6_FARM_GIANTSTAG_MOOSE_GROWN"],convertNut(1280),1),
new Recipe("T6_MOUNT_DIREWOLF", new Map([["T6_FARM_DIREWOLF_GROWN", 1], ["T6_LEATHER", 20]]),["T6_FARM_DIREWOLF_GROWN"],convertNut(1280),1),
new Recipe("T7_MOUNT_HORSE", new Map([["T7_FARM_HORSE_GROWN", 1], ["T7_LEATHER", 20]]),["T7_FARM_HORSE_GROWN"],convertNut(2560),1),
new Recipe("T7_MOUNT_ARMORED_HORSE", new Map([["T7_FARM_HORSE_GROWN", 1], ["T7_CLOTH", 10], ["T7_METALBAR", 20]]),["T7_FARM_HORSE_GROWN"],convertNut(3840),1),
new Recipe("T7_MOUNT_OX", new Map([["T7_FARM_OX_GROWN", 1], ["T7_PLANKS", 30]]),["T7_FARM_OX_GROWN"],convertNut(3840),1),
new Recipe("T7_MOUNT_DIREBOAR", new Map([["T7_FARM_DIREBOAR_GROWN", 1], ["T7_LEATHER", 20]]),["T7_FARM_DIREBOAR_GROWN"],convertNut(2560),1),
new Recipe("T7_MOUNT_SWAMPDRAGON", new Map([["T7_FARM_SWAMPDRAGON_GROWN", 1], ["T7_LEATHER", 20]]),["T7_FARM_SWAMPDRAGON_GROWN"],convertNut(2560),1),
new Recipe("T7_MOUNT_SWAMPDRAGON_AVALON_BASILISK", new Map([["T7_MOUNT_SWAMPDRAGON", 1], ["QUESTITEM_TOKEN_AVALON", 5000]]),["QUESTITEM_TOKEN_AVALON"],convertNut(3781.0),1),
new Recipe("T8_MOUNT_HORSE", new Map([["T8_FARM_HORSE_GROWN", 1], ["T8_LEATHER", 20]]),["T8_FARM_HORSE_GROWN"],convertNut(5120),1),
new Recipe("T8_MOUNT_ARMORED_HORSE", new Map([["T8_FARM_HORSE_GROWN", 1], ["T8_CLOTH", 10], ["T8_METALBAR", 20]]),["T8_FARM_HORSE_GROWN"],convertNut(7680),1),
new Recipe("T8_MOUNT_OX", new Map([["T8_FARM_OX_GROWN", 1], ["T8_PLANKS", 30]]),["T8_FARM_OX_GROWN"],convertNut(7680),1),
new Recipe("T8_MOUNT_DIREBEAR", new Map([["T8_FARM_DIREBEAR_GROWN", 1], ["T8_LEATHER", 20]]),["T8_FARM_DIREBEAR_GROWN"],convertNut(5120),1),
new Recipe("T8_MOUNT_MAMMOTH_TRANSPORT", new Map([["T8_FARM_MAMMOTH_GROWN", 1], ["T8_LEATHER", 20]]),["T8_FARM_MAMMOTH_GROWN"],convertNut(5120),1),
new Recipe("T8_MOUNT_MOABIRD_FW_BRIDGEWATCH_ELITE", new Map([["T8_FARM_MOABIRD_FW_BRIDGEWATCH_GROWN", 1], ["T8_LEATHER", 20], ["T1_FACTION_STEPPE_TOKEN_1", 20]]),["T8_FARM_MOABIRD_FW_BRIDGEWATCH_GROWN", "T1_FACTION_STEPPE_TOKEN_1"],convertNut(5120),1),
new Recipe("T8_MOUNT_DIREBEAR_FW_FORTSTERLING_ELITE", new Map([["T8_FARM_DIREBEAR_FW_FORTSTERLING_GROWN", 1], ["T8_LEATHER", 20], ["T1_FACTION_MOUNTAIN_TOKEN_1", 20]]),["T8_FARM_DIREBEAR_FW_FORTSTERLING_GROWN", "T1_FACTION_MOUNTAIN_TOKEN_1"],convertNut(5120),1),
new Recipe("T8_MOUNT_DIREBOAR_FW_LYMHURST_ELITE", new Map([["T8_FARM_DIREBOAR_FW_LYMHURST_GROWN", 1], ["T8_LEATHER", 20], ["T1_FACTION_FOREST_TOKEN_1", 20]]),["T8_FARM_DIREBOAR_FW_LYMHURST_GROWN", "T1_FACTION_FOREST_TOKEN_1"],convertNut(5120),1),
new Recipe("T8_MOUNT_RAM_FW_MARTLOCK_ELITE", new Map([["T8_FARM_RAM_FW_MARTLOCK_GROWN", 1], ["T8_LEATHER", 20], ["T1_FACTION_HIGHLAND_TOKEN_1", 20]]),["T8_FARM_RAM_FW_MARTLOCK_GROWN", "T1_FACTION_HIGHLAND_TOKEN_1"],convertNut(5120),1),
new Recipe("T8_MOUNT_SWAMPDRAGON_FW_THETFORD_ELITE", new Map([["T8_FARM_SWAMPDRAGON_FW_THETFORD_GROWN", 1], ["T8_LEATHER", 20], ["T1_FACTION_SWAMP_TOKEN_1", 20]]),["T8_FARM_SWAMPDRAGON_FW_THETFORD_GROWN", "T1_FACTION_SWAMP_TOKEN_1"],convertNut(5120),1),
new Recipe("T8_MOUNT_GREYWOLF_FW_CAERLEON_ELITE", new Map([["T8_FARM_GREYWOLF_FW_CAERLEON_GROWN", 1], ["T8_LEATHER", 20], ["T1_FACTION_CAERLEON_TOKEN_1", 20]]),["T8_FARM_GREYWOLF_FW_CAERLEON_GROWN", "T1_FACTION_CAERLEON_TOKEN_1"],convertNut(5120),1),
new Recipe("T8_MOUNT_OWL_FW_BRECILIEN_ELITE", new Map([["T8_FARM_OWL_FW_BRECILIEN_GROWN", 1], ["T8_LEATHER", 20], ["QUESTITEM_TOKEN_MISTS", 20]]),["T8_FARM_OWL_FW_BRECILIEN_GROWN", "QUESTITEM_TOKEN_MISTS"],convertNut(6400),1),
new Recipe("T8_MOUNT_HORSE_UNDEAD@1", new Map([["T8_MOUNT_HORSE", 1], ["T8_MOUNTUPGRADE_HORSE_CURSE", 1]]),["T8_MOUNT_HORSE", "T8_MOUNTUPGRADE_HORSE_CURSE"],convertNut(13918),1),
new Recipe("T8_MOUNT_COUGAR_KEEPER@1", new Map([["T5_MOUNT_COUGAR_KEEPER@1", 1], ["T8_MOUNTUPGRADE_COUGAR_KEEPER", 1]]),["T5_MOUNT_COUGAR_KEEPER", "T8_MOUNTUPGRADE_COUGAR_KEEPER"],convertNut(9438),1),
new Recipe("T8_MOUNT_ARMORED_HORSE_MORGANA@1", new Map([["T8_MOUNT_ARMORED_HORSE", 1], ["T8_MOUNTUPGRADE_HORSE_MORGANA", 1]]),["T8_MOUNT_ARMORED_HORSE", "T8_MOUNTUPGRADE_HORSE_MORGANA"],convertNut(16478),1),
new Recipe("T8_MOUNT_RABBIT_EASTER", new Map([["T8_FARM_RABBIT_EASTER_GROWN", 1], ["T8_LEATHER", 20]]),["T8_FARM_RABBIT_EASTER_GROWN"],convertNut(5120),1),
new Recipe("T8_MOUNT_RABBIT_EASTER_DARK@1", new Map([["T8_FARM_RABBIT_EASTER_GROWN_DARK", 1], ["T8_LEATHER", 20]]),["T8_FARM_RABBIT_EASTER_GROWN_DARK"],convertNut(5120),1),
    ]

    var itemmap = new Item_Map()

    async function updateTable(){
      //Theatrics
      $("#updateButton").text("Updating . . .")
      $("#updateButton").prop( "disabled", true );
      $("#tablearea").empty();

      itemmap.clearMap() //Must be used if working with quality.
      updateItemMap(itemmap,materials).then(x => updateTableValues()).then(x => {$("#updateButton").text("Update"); $("#updateButton").prop( "disabled", false )})
    }

    function updateTableValues(){
      createTableFromRecipesDifferentEnd(recipes, itemmap)
      updateProfit()
      changeProfitColor()
      bindSelectRow()
    }

    $(document).ready(function(){
      createNavBar()
      updateTable()
      $("#category").change(function() { updateTableValues() })
      $("#quality").change(function() { updateTableValues() })
      $("#enchantLevel").change(function() { updateTableValues() })
      $("#locations").change(function() { updateTableValues() })
      $("#endLocations").change(function() { updateTableValues() })
      $("#language").change(function() { updateTableValues() })
      $("#server").change(function() { updateTable() })
    })
