    var materials = "T3_FARM_HORSE_GROWN,T4_FARM_HORSE_GROWN,T5_FARM_HORSE_GROWN,T6_FARM_HORSE_GROWN,T7_FARM_HORSE_GROWN,T8_FARM_HORSE_GROWN,T8_FARM_RABBIT_EASTER_GROWN,T6_FARM_DIREWOLF_GROWN,T7_FARM_DIREBOAR_GROWN,T8_FARM_DIREBEAR_GROWN,T7_FARM_SWAMPDRAGON_GROWN,T8_FARM_MAMMOTH_GROWN,T5_FARM_COUGAR_GROWN,T8_FARM_DIREWOLF_GROWN,T4_FARM_GIANTSTAG_GROWN,T6_FARM_GIANTSTAG_GROWN,T6_FARM_GIANTSTAG_MOOSE_GROWN,T5_FARM_MOABIRD_FW_BRIDGEWATCH_GROWN,T5_FARM_DIREBEAR_FW_FORTSTERLING_GROWN,T5_FARM_DIREBOAR_FW_LYMHURST_GROWN ,T5_FARM_RAM_FW_MARTLOCK_GROWN,T5_FARM_SWAMPDRAGON_FW_THETFORD_GROWN,T5_FARM_GREYWOLF_FW_CAERLEON_GROWN,T8_FARM_MOABIRD_FW_BRIDGEWATCH_GROWN,T8_FARM_DIREBEAR_FW_FORTSTERLING_GROWN,T8_FARM_DIREBOAR_FW_LYMHURST_GROWN,T8_FARM_RAM_FW_MARTLOCK_GROWN,T8_FARM_SWAMPDRAGON_FW_THETFORD_GROWN,T8_FARM_GREYWOLF_FW_CAERLEON_GROWN,T3_LEATHER,T4_LEATHER,T5_LEATHER,T6_LEATHER,T7_LEATHER,T8_LEATHER,T5_METALBAR,T6_METALBAR,T7_METALBAR,T8_METALBAR,T1_FACTION_FOREST_TOKEN_1,T1_FACTION_HIGHLAND_TOKEN_1 ,T1_FACTION_STEPPE_TOKEN_1,T1_FACTION_MOUNTAIN_TOKEN_1,T1_FACTION_SWAMP_TOKEN_1,T1_FACTION_CAERLEON_TOKEN_1,QUESTITEM_TOKEN_AVALON,T2_CLOTH,T3_CLOTH,T4_CLOTH,T5_CLOTH,T6_CLOTH,T7_CLOTH,T8_CLOTH,T7_MOUNT_SWAMPDRAGON,T8_MOUNT_HORSE,T5_MOUNT_COUGAR_KEEPER@1,T8_MOUNT_ARMORED_HORSE,T3_PLANKS,T4_PLANKS,T5_PLANKS,T6_PLANKS,T7_PLANKS,T8_PLANKS,T3_FARM_OX_GROWN,T4_FARM_OX_GROWN,T5_FARM_OX_GROWN,T6_FARM_OX_GROWN,T7_FARM_OX_GROWN,T8_FARM_OX_GROWN,T8_MOUNTUPGRADE_HORSE_CURSE,T8_MOUNTUPGRADE_COUGAR_KEEPER,T8_MOUNTUPGRADE_HORSE_MORGANA"
    var products = "T3_MOUNT_HORSE,T4_MOUNT_HORSE,T5_MOUNT_HORSE,T6_MOUNT_HORSE,T7_MOUNT_HORSE,T8_MOUNT_HORSE,T5_MOUNT_ARMORED_HORSE,T6_MOUNT_ARMORED_HORSE,T7_MOUNT_ARMORED_HORSE,T8_MOUNT_ARMORED_HORSE,T3_MOUNT_OX,T4_MOUNT_OX,T5_MOUNT_OX,T6_MOUNT_OX,T7_MOUNT_OX,T8_MOUNT_OX,T4_MOUNT_GIANTSTAG,T6_MOUNT_GIANTSTAG_MOOSE,T6_MOUNT_DIREWOLF,T7_MOUNT_DIREBOAR,T7_MOUNT_SWAMPDRAGON,T8_MOUNT_DIREBEAR,T8_MOUNT_MAMMOTH_TRANSPORT,T5_MOUNT_MOABIRD_FW_BRIDGEWATCH,T5_MOUNT_DIREBEAR_FW_FORTSTERLING,T5_MOUNT_DIREBOAR_FW_LYMHURST,T5_MOUNT_RAM_FW_MARTLOCK,T5_MOUNT_SWAMPDRAGON_FW_THETFORD,T5_MOUNT_GREYWOLF_FW_CAERLEON,T8_MOUNT_MOABIRD_FW_BRIDGEWATCH_ELITE,T8_MOUNT_DIREBEAR_FW_FORTSTERLING_ELITE,T8_MOUNT_DIREBOAR_FW_LYMHURST_ELITE,T8_MOUNT_RAM_FW_MARTLOCK_ELITE,T8_MOUNT_SWAMPDRAGON_FW_THETFORD_ELITE,T8_MOUNT_GREYWOLF_FW_CAERLEON_ELITE,T8_MOUNT_MAMMOTH_BATTLE@1,T7_MOUNT_SWAMPDRAGON_BATTLE,T7_MOUNT_ARMORED_SWAMPDRAGON_BATTLE,T6_MOUNT_SIEGE_BALLISTA,T8_MOUNT_HORSE_UNDEAD@1,T5_MOUNT_COUGAR_KEEPER@1,T8_MOUNT_COUGAR_KEEPER@1,T8_MOUNT_ARMORED_HORSE_MORGANA@1,T8_MOUNT_RABBIT_EASTER,UNIQUE_MOUNT_RAM_XMAS,T7_MOUNT_SWAMPDRAGON_AVALON_BASILISK,UNIQUE_MOUNT_RAM_TELLAFRIEND,UNIQUE_MOUNT_MOABIRD_TELLAFRIEND,UNIQUE_MOUNT_BAT_TELLAFRIEND,UNIQUE_MOUNT_GIANTTOAD_TELLAFRIEND,UNIQUE_MOUNT_PANDA_TELLAFRIEND,UNIQUE_MOUNT_GIANTTOAD_02_TELLAFRIEND,T5_MOUNT_ARMORED_HORSE_SKIN_01,T6_MOUNT_ARMORED_HORSE_SKIN_01,T7_MOUNT_ARMORED_HORSE_SKIN_01,T8_MOUNT_ARMORED_HORSE_SKIN_01,UNIQUE_MOUNT_BAT_PERSONAL,T7_MOUNT_MONITORLIZARD_ADC,T7_MOUNT_HUSKY_ADC,T6_MOUNT_FROSTRAM_ADC,T7_MOUNT_TERRORBIRD_ADC,UNIQUE_MOUNT_BEAR_KEEPER_ADC,UNIQUE_MOUNT_BLACK_PANTHER_ADC,UNIQUE_MOUNT_MORGANA_RAVEN_ADC,UNIQUE_MOUNT_GIANT_HORSE_ADC,UNIQUE_MOUNT_UNDEAD_DIREBOAR_ADC,UNIQUE_MOUNT_DIVINE_OWL_ADC,UNIQUE_MOUNT_HERETIC_MULE_ADC,UNIQUE_MOUNT_RHINO_SEASON_CRYSTAL,UNIQUE_MOUNT_RHINO_SEASON_GOLD,UNIQUE_MOUNT_RHINO_SEASON_SILVER,UNIQUE_MOUNT_RHINO_SEASON_BRONZE,UNIQUE_MOUNT_TOWER_CHARIOT_CRYSTAL,UNIQUE_MOUNT_TOWER_CHARIOT_GOLD,UNIQUE_MOUNT_TOWER_CHARIOT_SILVER,UNIQUE_MOUNT_ARMORED_EAGLE_CRYSTAL,UNIQUE_MOUNT_ARMORED_EAGLE_GOLD,UNIQUE_MOUNT_ARMORED_EAGLE_SILVER,UNIQUE_MOUNT_BEETLE_CRYSTAL,UNIQUE_MOUNT_BEETLE_GOLD,UNIQUE_MOUNT_BEETLE_SILVER,UNIQUE_MOUNT_BEHEMOTH_CRYSTAL,UNIQUE_MOUNT_BEHEMOTH_GOLD,UNIQUE_MOUNT_BEHEMOTH_SILVER,UNIQUE_MOUNT_ENT_CRYSTAL,UNIQUE_MOUNT_ENT_GOLD,UNIQUE_MOUNT_ENT_SILVER,UNIQUE_MOUNT_BATTLESPIDER_CRYSTAL,UNIQUE_MOUNT_BATTLESPIDER_GOLD,UNIQUE_MOUNT_BATTLESPIDER_SILVER,UNIQUE_MOUNT_BASTION_CRYSTAL,UNIQUE_MOUNT_BASTION_GOLD,UNIQUE_MOUNT_BASTION_SILVER,UNIQUE_MOUNT_JUGGERNAUT_CRYSTAL,UNIQUE_MOUNT_JUGGERNAUT_GOLD,UNIQUE_MOUNT_JUGGERNAUT_SILVER,UNIQUE_MOUNT_TANKBEETLE_CRYSTAL,UNIQUE_MOUNT_TANKBEETLE_GOLD,UNIQUE_MOUNT_TANKBEETLE_SILVER,UNIQUE_MOUNT_RHINO_TELLAFRIEND,UNIQUE_MOUNT_GIANTSTAG_FOUNDER_EPIC"
               ///new Recipe(resultId, ingredientMap, nutrition, quantity)
    var recipes = [
                  new Recipe("T3_MOUNT_HORSE", new Map([["T3_FARM_HORSE_GROWN",1],["T3_LEATHER",20]]), 0.18, 1),
                  new Recipe("T4_MOUNT_HORSE", new Map([["T4_FARM_HORSE_GROWN",1],["T4_LEATHER",20]]), 0.36, 1),
                  new Recipe("T5_MOUNT_HORSE", new Map([["T5_FARM_HORSE_GROWN",1],["T5_LEATHER",20]]), 0.72, 1),
                  new Recipe("T6_MOUNT_HORSE", new Map([["T6_FARM_HORSE_GROWN",1],["T6_LEATHER",20]]), 1.44, 1),
                  new Recipe("T7_MOUNT_HORSE", new Map([["T7_FARM_HORSE_GROWN",1],["T7_LEATHER",20]]), 2.88, 1),
                  new Recipe("T8_MOUNT_HORSE", new Map([["T8_FARM_HORSE_GROWN",1],["T8_LEATHER",20]]), 5.76, 1),
                  new Recipe("T5_MOUNT_ARMORED_HORSE", new Map([["T5_FARM_HORSE_GROWN",1],["T5_CLOTH",10],["T5_METALBAR",20]]),1.08,1),
                  new Recipe("T6_MOUNT_ARMORED_HORSE", new Map([["T6_FARM_HORSE_GROWN",1],["T6_CLOTH",10],["T6_METALBAR",20]]),2.16,1),
                  new Recipe("T7_MOUNT_ARMORED_HORSE", new Map([["T7_FARM_HORSE_GROWN",1],["T7_CLOTH",10],["T7_METALBAR",20]]),4.32,1),
                  new Recipe("T8_MOUNT_ARMORED_HORSE", new Map([["T8_FARM_HORSE_GROWN",1],["T8_CLOTH",10],["T8_METALBAR",20]]),8.64,1),
                  new Recipe("T3_MOUNT_OX", new Map([["T3_FARM_OX_GROWN",1],["T3_PLANKS",30]]),0.27,1),
                  new Recipe("T4_MOUNT_OX", new Map([["T4_FARM_OX_GROWN",1],["T4_PLANKS",30]]),0.54,1),
                  new Recipe("T5_MOUNT_OX", new Map([["T5_FARM_OX_GROWN",1],["T5_PLANKS",30]]),1.08,1),
                  new Recipe("T6_MOUNT_OX", new Map([["T6_FARM_OX_GROWN",1],["T6_PLANKS",30]]),2.16,1),
                  new Recipe("T7_MOUNT_OX", new Map([["T7_FARM_OX_GROWN",1],["T7_PLANKS",30]]),4.32,1),
                  new Recipe("T8_MOUNT_OX", new Map([["T8_FARM_OX_GROWN",1],["T8_PLANKS",30]]),8.64,1),
                  new Recipe("T4_MOUNT_GIANTSTAG", new Map([["T4_FARM_GIANTSTAG_GROWN",1],["T4_LEATHER",20]]),0.36,1),
                  new Recipe("T5_MOUNT_COUGAR_KEEPER@1", new Map([["T5_FARM_COUGAR_GROWN",1],["T5_LEATHER",20]]),0.72,1),
                  new Recipe("T5_MOUNT_MOABIRD_FW_BRIDGEWATCH", new Map([["T5_FARM_MOABIRD_FW_BRIDGEWATCH_GROWN",1],["T5_LEATHER",20],["T1_FACTION_STEPPE_TOKEN_1",5]]),0.72,1),
                  new Recipe("T5_MOUNT_DIREBEAR_FW_FORTSTERLING", new Map([["T5_FARM_DIREBEAR_FW_FORTSTERLING_GROWN",1],["T5_LEATHER",20],["T1_FACTION_MOUNTAIN_TOKEN_1",5]]),0.72,1),
                  new Recipe("T5_MOUNT_DIREBOAR_FW_LYMHURST", new Map([["T5_FARM_DIREBOAR_FW_LYMHURST_GROWN",1],["T5_LEATHER",20],["T1_FACTION_FOREST_TOKEN_1",5]]),0.72,1),
                  new Recipe("T5_MOUNT_RAM_FW_MARTLOCK", new Map([["T5_FARM_RAM_FW_MARTLOCK_GROWN",1],["T5_LEATHER",20],["T1_FACTION_HIGHLAND_TOKEN_1",5]]),0.72,1),
                  new Recipe("T5_MOUNT_SWAMPDRAGON_FW_THETFORD", new Map([["T5_FARM_SWAMPDRAGON_FW_THETFORD_GROWN",1],["T5_LEATHER",20],["T1_FACTION_SWAMP_TOKEN_1",5]]),0.72,1),
                  new Recipe("T5_MOUNT_GREYWOLF_FW_CAERLEON", new Map([["T5_FARM_GREYWOLF_FW_CAERLEON_GROWN",1],["T5_LEATHER",20],["T1_FACTION_CAERLEON_TOKEN_1",5]]),0.72,1),
                  new Recipe("T6_MOUNT_DIREWOLF", new Map([["T6_FARM_DIREWOLF_GROWN",1],["T6_LEATHER",20]]),1.44,1),
                  new Recipe("T6_MOUNT_GIANTSTAG_MOOSE", new Map([["T6_FARM_GIANTSTAG_MOOSE_GROWN",1],["T6_LEATHER",20]]),1.44,1),
                  new Recipe("T7_MOUNT_DIREBOAR", new Map([["T7_FARM_DIREBOAR_GROWN",1],["T7_LEATHER",20]]),2.88,1),
                  new Recipe("T7_MOUNT_SWAMPDRAGON", new Map([["T7_FARM_SWAMPDRAGON_GROWN",1],["T7_LEATHER",20]]),2.88,1),
                  new Recipe("T7_MOUNT_SWAMPDRAGON_AVALON_BASILISK", new Map([["T7_MOUNT_SWAMPDRAGON",1],["QUESTITEM_TOKEN_AVALON",5000]]),4.253636363636363636363,1),
                  new Recipe("T8_MOUNT_DIREBEAR", new Map([["T8_FARM_DIREBEAR_GROWN",1],["T8_LEATHER",20]]),5.76,1),
                  new Recipe("T8_MOUNT_HORSE_UNDEAD@1", new Map([["T8_MOUNT_HORSE",1],["T8_MOUNTUPGRADE_HORSE_CURSE",1]]),15.657727272727272727272727272727,1),
                  new Recipe("T8_MOUNT_COUGAR_KEEPER@1", new Map([["T5_MOUNT_COUGAR_KEEPER@1",1],["T8_MOUNTUPGRADE_COUGAR_KEEPER",1]]),10.617727272727272727272727272727,1),
                  new Recipe("T8_MOUNT_ARMORED_HORSE_MORGANA@1", new Map([["T8_MOUNT_ARMORED_HORSE",1],["T8_MOUNTUPGRADE_HORSE_MORGANA",1]]),18.537727272727272727272727272727,1),
                  new Recipe("T8_MOUNT_MAMMOTH_TRANSPORT", new Map([["T8_FARM_MAMMOTH_GROWN",1],["T8_LEATHER",20]]),5.76,1),
                  new Recipe("T8_MOUNT_RABBIT_EASTER", new Map([["T8_FARM_RABBIT_EASTER_GROWN",1],["T8_LEATHER",20]]),5.76,1),
                  new Recipe("T8_MOUNT_MOABIRD_FW_BRIDGEWATCH_ELITE",new Map([["T8_FARM_MOABIRD_FW_BRIDGEWATCH_GROWN",1],["T8_LEATHER",20],["T1_FACTION_STEPPE_TOKEN_1",20]]),5.76,1),
                  new Recipe("T8_MOUNT_DIREBEAR_FW_FORTSTERLING_ELITE",new Map([["T8_FARM_DIREBEAR_FW_FORTSTERLING_GROWN",1],["T8_LEATHER",20],["T1_FACTION_MOUNTAIN_TOKEN_1",20]]),5.76,1),
                  new Recipe("T8_MOUNT_DIREBOAR_FW_LYMHURST_ELITE",new Map([["T8_FARM_DIREBOAR_FW_LYMHURST_GROWN",1],["T8_LEATHER",20],["T1_FACTION_FOREST_TOKEN_1",20]]),5.76,1),
                  new Recipe("T8_MOUNT_RAM_FW_MARTLOCK_ELITE",new Map([["T8_FARM_RAM_FW_MARTLOCK_GROWN",1],["T8_LEATHER",20],["T1_FACTION_HIGHLAND_TOKEN_1",20]]),5.76,1),
                  new Recipe("T8_MOUNT_SWAMPDRAGON_FW_THETFORD_ELITE",new Map([["T8_FARM_SWAMPDRAGON_FW_THETFORD_GROWN",1],["T8_LEATHER",20],["T1_FACTION_SWAMP_TOKEN_1",20]]),5.76,1),
                  new Recipe("T8_MOUNT_GREYWOLF_FW_CAERLEON_ELITE",new Map([["T8_FARM_GREYWOLF_FW_CAERLEON_GROWN",1],["T8_LEATHER",20],["T1_FACTION_CAERLEON_TOKEN_1",20]]),5.76,1)
                  ]

    var itemmap = new Item_Map()

    async function updateTable(){
      itemmap.clearMap() //Must be used if working with quality.
      updateItemMap(itemmap,products).then(x => updateItemMap(itemmap, materials)).then(x => createTableFromRecipes(recipes, itemmap)).then( x => changeProfitColor() ).then(x => bindSelectRow())
    }
    $(document).ready(function(){
      createNavBar()
      updateTable()
    })